SIMULATION_STEP_SECONDS = 1
SIMULATION_TIME_STEP_HOURS = 0.25

BATTERY_CAPACITY_KWH = 10.0
BATTERY_SOC_INITIAL = 50.0
BATTERY_MAX_CHARGE_KW = 3.0
BATTERY_MAX_DISCHARGE_KW = 3.0

MQTT_BROKER_HOST = "localhost"
MQTT_BROKER_PORT = 1883
MQTT_KEEPALIVE = 60
MQTT_CLIENT_ID = "renewable_simulator_01"
MQTT_TOPIC_PREFIX = "renewable"

MONGO_URI = "mongodb://localhost:27017"
MONGO_DB_NAME = "renewable_db"
MONGO_COLLECTION_TELEMETRY = "telemetry"

API_HOST = "127.0.0.1"
API_PORT = 8000